version: '3.8'
services:
  map_db:
    image: postgres:13
    restart: unless-stopped
    container_name: map_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hiachi20
      POSTGRES_DB: Map
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:hiachi20@map_db:5432/Map?schema=public
      SECRET_KEY_JWT: "MILLAVE123"
      BLOCKCHAIN_SERVICE_URL: http://blockchain-api:3002
      TOKEN_ADDRESS: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
      APP_WALLET_ADDRESS: 0xdF68EE8cB29069042451Baa024b742e2B04AeB21
    ports:
      - "3001:3001"
    depends_on:
      map_db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    networks:
      - app-network
      - blockchain_network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  blockchain_network:
    name: backend-blockchain-sw1_blockchain_network
    external: true